# Generated by Django 4.0.5 on 2022-06-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='owner_contact',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name="Owner's Contact Number"),
        ),
    ]
