# Generated by Django 4.0.5 on 2022-06-16 06:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_boat_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='post_rate',
            field=models.FloatField(default=1000, help_text='(in milliseconds)', verbose_name='Server Post Rate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='available_until',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2022, 6, 16))], verbose_name='Available Until'),
        ),
    ]
