# Generated by Django 4.0.5 on 2022-07-13 00:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_boat_height_alter_boat_length_alter_boat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='available_until',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2022, 7, 13))], verbose_name='Available Until'),
        ),
        migrations.AlterField(
            model_name='record',
            name='altitude',
            field=models.FloatField(blank=True, default=None, help_text='(in meters)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Altitude'),
        ),
    ]
