# Generated by Django 4.0.5 on 2022-07-13 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alter_bulletin_available_until_alter_record_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='altitude',
            field=models.FloatField(default=0, help_text='(in meters)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Altitude'),
        ),
    ]
