# Generated by Django 4.0.5 on 2022-10-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_boat_registered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registered at'),
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
    ]
