# Generated by Django 4.0.5 on 2022-10-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_alter_boat_registered_at_alter_record_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sent_timestamp',
            field=models.CharField(default='', max_length=25, verbose_name='Time Sent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time Received'),
        ),
    ]
