# Generated by Django 4.0.5 on 2023-05-19 04:19

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_record_sent_timestamp_alter_record_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='signalStrength',
            field=models.PositiveSmallIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='available_until',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 5, 19))], verbose_name='Available Until'),
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Ended At')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.boat', verbose_name='Boat')),
            ],
        ),
        migrations.CreateModel(
            name='LocalReadingAndError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readings', models.TextField()),
                ('errors', models.TextField(blank=True, default=None, null=True)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.boat', verbose_name='Boat')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='voyage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.voyage', verbose_name='Voyage'),
            preserve_default=False,
        ),
    ]
