# Generated by Django 4.0.5 on 2025-07-31 03:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_alter_bulletin_available_until_focusboat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='available_until',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 7, 31))], verbose_name='Available Until'),
        ),
    ]
