# Generated by Django 4.0.5 on 2025-10-31 13:10

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_alter_bulletin_available_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Adopter Code')),
                ('name', models.CharField(max_length=100, verbose_name="Adopter's Name")),
                ('address', models.CharField(max_length=250, verbose_name="Adopter's Address")),
                ('contact_person', models.CharField(max_length=100, verbose_name="Adopter's Contact Person")),
                ('email', models.EmailField(max_length=250, verbose_name="Adopter's Email")),
                ('phone', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name="Adopter's Phone")),
                ('map_title', models.CharField(default='Map', max_length=100, verbose_name='_(Map Title)')),
                ('map_center_lat', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='_(Map Center Latitude)')),
                ('map_center_lng', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='_(Map Center Longitude)')),
                ('map_zoom', models.IntegerField(default=12, verbose_name='_(Map Zoom)')),
            ],
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='available_until',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 10, 31))], verbose_name='Available Until'),
        ),
        migrations.AlterUniqueTogether(
            name='boat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='boat',
            name='adopter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.adopter', verbose_name='Adopter'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='adopter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.adopter', verbose_name='Adopter'),
        ),
        migrations.AddField(
            model_name='focusboat',
            name='adopter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.adopter', verbose_name='Adopter'),
        ),
        migrations.AddField(
            model_name='setting',
            name='adopter',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.adopter', verbose_name='Adopter'),
        ),
        migrations.AlterUniqueTogether(
            name='boat',
            unique_together={('name', 'owner', 'adopter')},
        ),
    ]
