# Generated by Django 4.0.5 on 2025-10-31 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_adopter_alter_bulletin_available_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='map_center_lat',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Map Center Latitude'),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='map_center_lng',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Map Center Longitude'),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='map_title',
            field=models.CharField(default='Map', max_length=100, verbose_name='Map Title'),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='map_zoom',
            field=models.IntegerField(default=12, verbose_name='Map Zoom'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='critical_pitch_angle',
            field=models.FloatField(default=15.0, help_text='(in degrees)', verbose_name='Critical Pitch Angle'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='critical_roll_angle',
            field=models.FloatField(default=20.0, help_text='(in degrees)', verbose_name='Critical Roll Angle'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='post_rate',
            field=models.FloatField(default=60000.0, help_text='(in milliseconds)', verbose_name='Server Post Rate'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='reading_rate',
            field=models.FloatField(default=250.0, help_text='(in milliseconds)', verbose_name='Reading Rate'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='saving_rate',
            field=models.FloatField(default=60000.0, help_text='(in milliseconds)', verbose_name='Saving Rate'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sms_rate',
            field=models.FloatField(default=60000.0, help_text='(in milliseconds)', verbose_name='SMS Rate'),
        ),
    ]
